# Generated by Django 6.0.1 on 2026-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopgon_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', '일반유저'), ('vip', 'VIP'), ('admin', '관리자')], default='user', max_length=10),
        ),
    ]
